modLoader = "javafml"
loaderVersion = "[47,)"
license = "GPL-3.0"

[[mixins]]
config = "townstead.mixins.json"

[[mods]]
modId = "townstead"
version = "${version}"
displayName = "Townstead"
authors = "AetherianArtificer"
description = '''An unofficial expansion for MCA Reborn with additional villager needs, buildings, jobs, and mod integrations.'''
logoFile = "townstead-title-hd.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/townstead"

[modproperties.townstead]
catalogueImageIcon = "townstead-title-square-hd.png"

[[dependencies.townstead]]
modId = "forge"
mandatory = true
versionRange = "[47.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.townstead]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.townstead]]
modId = "mca"
mandatory = true
versionRange = "[7.6.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.townstead]]
modId = "configured"
mandatory = false
versionRange = "[2.2.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.townstead]]
modId = "modonomicon"
mandatory = false
versionRange = "[1.79,)"
ordering = "AFTER"
side = "BOTH"
